on:
  workflow_dispatch:
    inputs:
      input1:
        description: 'input1'
        required: false
        default: 'input1'
        type: string
jobs:
  fjei:
    runs-on: ubuntu-latest
    steps:
      - run: echo "fadsf"
  
